#### PROJECT SETTINGS ####
BIN_NAME := nttt
CXX ?= g++
SRC_EXT = cpp
SRC_PATH = .
LIBS =
COMPILE_FLAGS = -std=c++11 -Wall -Wextra -g
RCOMPILE_FLAGS = -D NDEBUG
DCOMPILE_FLAGS = -D DEBUG
INCLUDES = -Iinclude $(SRC_PATH)
LINK_FLAGS =
RLINK_FLAGS =
DLINK_FLAGS =
DESTDIR = /
INSTALL_PREFIX = usr/local
#### END PROJECT SETTINGS ####
